### ISSUE TITLE
Configuração para parcelamento/desconto padrão

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-pagseguro#11]
No admin settings já temos um objeto `discount` para boleto, no `list_payments` este mesmo desconto (se preenchido) também deve ser retornado no `discount_option` além do `payment_gateways[].discount` (já retornado).

O `installments_option` pode ser definido com um objeto a mais no admin settings (mesmo que a lista de parcelas seja buscada do PagSeguro) para que o lojista possa especificar a opção de parcelamento em destaque via PagSeguro, como feito [aqui para o MercadoPago](https://github.com/ecomplus/app-mercadopago/blob/master/assets/application.json#L129-L165) (no MP a lista de parcelas funciona exatamente como no PagSeguro).

**Comment by talissonf** [comment]
> No admin settings já temos um objeto `discount` para boleto, no `list_payments` este mesmo desconto (se preenchido) também deve ser retornado no `discount_option` além do `payment_gateways[].discount` (já retornado).
> 

Mais isso já é feito;

https://github.com/ecomclub/app-pagseguro/blob/0f50b3aa925aef7af6d58747d541ec1bedb1a3b3/routes/ecom/modules/list-payments.js#L34

> O `installments_option` pode ser definido com um objeto a mais no admin settings (mesmo que a lista de parcelas seja buscada do PagSeguro) para que o lojista possa especificar a opção de parcelamento em destaque via PagSeguro, como feito [aqui para o MercadoPago](https://github.com/ecomplus/app-mercadopago/blob/master/assets/application.json#L129-L165) (no MP a lista de parcelas funciona exatamente como no PagSeguro).

Mas se eu usar o que for definido pelo lojista, no installments_option, eu vou sobrescrever as opções de installments enviadas pelo pagseguro.

https://github.com/ecomclub/app-pagseguro/blob/0f50b3aa925aef7af6d58747d541ec1bedb1a3b3/routes/ecom/modules/list-payments.js#L99

**Comment by talissonf** [comment]
@leomp12

**Comment by leomp12** [comment]
> Mais isso já é feito;

Pra desconto só, né?

> Mas se eu usar o que for definido pelo lojista, no installments_option, eu vou sobrescrever as opções de installments enviadas pelo pagseguro.

Não sô, negócio é que agora você só mostra o parcelamento padrão se tiver opção sem juros, certo? Em vez disto você pode deixar o lojista especificar opcionalmente o parcelamento padrão (`installments_option`), pra ficar consistente com o PagSeguro basta que ele insira uma configuração que condiz com o parcelamento que ele tem lá, é o mesmo que eu fiz no MP.

Se o lojista não configurar o parcelamento padrão você continua preenchendo a propriedade `installment_options` apenas se houver opção de parcelamento sem juros.

A lista de parcelas (`installment_options`) continua sendo buscada no PagSeguro, só ela é usada no checkout.

**Comment by leomp12** [comment]
@matheusgnreis

**Comment by talissonf** [comment]
@matheusgnreis @leomp12 é necessário atualizar o app para o opção de installments_option aparecer para o lojista. 
Na 1011 ja tem uma versão recente instalada, caso for testar la.

**Comment by matheusgnreis** [comment]
Valeu talisson, vou verificar
