### ISSUE TITLE
Cliente recebeu notificação de um pedido `Desconhecido`

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-pagseguro#18]
A notificação segue abaixo:
    {
      "transaction_id": "604582876d50911b6056f69a",
      "date_time": "2021-03-22T03:54:34.385Z",
      "status": "unknown",
      "notification_code": "EAA599-C1CBC9CBC9E2-ACC4D80F8BE6-C4C762",
      "flags": [
        "cpm:patch",
        "pagseguro"
      ],
      "customer_notified": false,
      "_id": "605814fa4b9484460867cd6e"
    }

**Comment by leomp12** [comment]
Uai, até aí nada de mais, de fato o status `unknown` existe pro caso de um status não maepado, sabe pelo menos qual é o status no PagSeguro?

**Comment by matheusgnreis** [comment]
Não sei, mas foi logo depois de pago. Talvez seja algo relacionado a estorno ou devolvido.
