### ISSUE TITLE
Fixar ícones dos gateways

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-pagseguro#2]
O app está retornando o mesmo banner do pagseguro em todos os métodos, o problema é que este banner mostra ícones de cartão e boleto, no checkout aparece o banner repetido em todas as opções e fica ambíguo:

![Screenshot_2019-10-04 Finalizar compra · My Shop](https://user-images.githubusercontent.com/10326572/66217665-1c910c80-e69e-11e9-8ab0-a1c62316d956.png)

O correto seria um banner pra cartão, um pra boleto e um pra débito, com os ícones corretos, ou apenas para cartão (sem `icon` nas outras opções) e apenas com ícones de bandeiras de cartão (sem boleto).

**Comment by leomp12** [comment]
@vitorrgg consegue os banners corretos por favor?

**Comment by talissonf** [comment]
Done!

**Comment by leomp12** [comment]
@talissonf Tá com `http://`, o navegador acusa erro por conteúdo misto, favor corrigir para:
`https://e-com.club/mass/ftp/others/pagseguro-cr%C3%A9dito.png`

**Comment by leomp12** [comment]
@vitorrgg não se coloca acento em URL, se puder corrigir pra `pagseguro-credito.png` em vez de `pagseguro-cr%C3%A9dito.png` por favor.

**Comment by talissonf** [comment]
@vitorrgg se puder remover os acento do nome dos arquivos só pra fechar esse issue.
