### ISSUE TITLE
Erros de conexão (?)

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-pagseguro#3]
```console
ecomplus-integrations [Fri Nov 29 2019 17:21:15 GMT-0200 (Brasilia Summer Time)] 
LIST_PAYMENTS_ERR
getaddrinfo ENOTFOUND ws.pagseguro.uol.com.br ws.pagseguro.uol.com.br:443
  ---  //  ---  

ecomplus-integrations [Mon Dec 02 2019 12:20:27 GMT-0200 (Brasilia Summer Time)] 
LIST_PAYMENTS_ERR
read ECONNRESET
  ---  //  ---
```

O primeiro erro parece instabilidade do PagSeguro mesmo, fiquei na dúvida do segundo, não tem nenhuma descrição dele no log, é um bug?
Se também for problema com o servidor do PagSeguro não é um bug, mas de qualquer forma é bom ter uma descrição melhor na mensagem do erro.

**Comment by talissonf** [comment]
Então, eu ja tive esses erros em outros momentos e era instabilidade do pags, mas vou melhorar a descrição.

**Comment by leomp12** [comment]
Nestes casos, não conseguindo contectar ao servidor do PagSeguro você retorna um erro 400 com uma mensagem que descreva o erro corretamente no list payments, sem registrar em log pra não ficar floodando.
Caso esteja em create transaction ou em list payments mas com `params.is_checkout_confirmation === true` você registra em log (aí já é um cenário mais crítico), preferencialmente salvando o order ID no log também (ex.: `Erro trying to create transaction for order ${_id}`).
