### ISSUE TITLE
Nome do cliente incorreto (undefined)

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-pagseguro#5]
@talissonf pode dar uma olhada nisso aqui por favor?

![image](https://user-images.githubusercontent.com/10326572/71820538-2562f700-306e-11ea-8546-d36b61dd4dea.png)

O nome do cliente está correto no cadastro da loja, e também é enviado corretamente para os outros intermediadores de pagamento nesta loja, o problema só ocorre no PagSeguro.

**Comment by talissonf** [comment]
@leomp12 eu realmente acho que o problema é com o pagseguro pois na criação do transação só existe um campo chamado `name` https://dev.pagseguro.uol.com.br/reference#split-exemplos-de-implementacao .
E esse campo eu pego os dados da propriedade `buyer.fullname` e envio na criação da transação.
E recentemente eu fiz uma compra numa loja chamada nephew e todos os e-mails que eu recebi do pagseguro sobre a compra vieram com esse bug também.

![Captura de tela de 2020-01-06 11-16-05](https://user-images.githubusercontent.com/14341511/71823861-01f07a00-3077-11ea-9b87-92271cf71938.png)

**Comment by leomp12** [comment]
Geralmente isto funciona corretamente em outras plataformas, sempre funcionou na E-Com Club por exemplo, e continua funcionando, então não é uma limitação do PagSeguro.
Talvez tenha alguma outra forma de enviar o nome na integração, ou talvez o `buyer.fullname` esteja sendo enviado incorreto em alguma situação, chegou a verificar isto?
Com certeza alguma solução existe, e não podemos deixar desta forma...

> Edit.: Pelos testes que eu fiz na 1011 o `buyer.fullname` parece estar sendo enviado corretamente, mas não consigo ver no PagSeguro como ficou, acho que está em uma conta sua mesmo.

**Comment by talissonf** [comment]
Eu não cheguei a testar o dados que eu tava recebendo no create-transaction e parece que é o storefront-app que está enviando esse undefined quando o nome tem mais de 3 nomes.

```
"buyer": {
            "email": "talissonf@gmail.com",
            "fullname": "Talisson undefined Ferreira",
            "doc_number": "11605468606",
            "registry_type": "p",
            "birth_date": {
                "day": 1,
                "month": 9,
                "year": 1993
            },
            "gender": "x",
            "phone": {
                "number": "31999665477"
            },
            "customer_id": "5c45f34fdff7463b8b7cb2a7"
        },
```

**Comment by leomp12** [comment]
Estranho porque eu testei com 3 nomes e não vi isto no network, não testei foi com 2 nomes...
Você chegou a verificar o body enviado no frontend?

**Comment by talissonf** [comment]
Na verdade acho que é o modulo que envia o nome errado pro app, eu to olhando o historico dos testes que fiz no local e todos que tem mais de 3 nomes vem assim 

```javascript
       "buyer": {
            "email": "suporte@e-com.club",
            "fullname": "Matheus undefined Suporte",
            "doc_number": "08728398696",
            "registry_type": "p",
            "birth_date": {
                "day": 12,
                "month": 12,
                "year": 1990
            },
            "phone": {
                "number": "12999288238"
            },
            "customer_id": "5d530ac35753286eadb9f95f"
        },```

**Comment by leomp12** [comment]
Na verdade eu acho que é no storefront app mesmo (no frontend), mas pra 2 nomes:

https://github.com/ecomclub/storefront-app/blob/master/src/store/modules/checkout.js#L20

Daria exatamente este problema..
Vou corrigir isto agora, tô achando estranho é você falando que tá acontecendo é com mais de 3 nomes, não é _menos_ de 3 nomes mesmo? :thinking:

**Comment by talissonf** [comment]
É com menos de 3 nomes :$

**Comment by leomp12** [comment]
Beleza, valeu!
